//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FAPSEntities : DbContext
    {
        public FAPSEntities()
            : base("name=FAPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidaturas> Candidaturas { get; set; }
        public virtual DbSet<Curriculo> Curriculo { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Vagas> Vagas { get; set; }
        public virtual DbSet<Interview> Interview { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
    }
}
