//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faps.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedback
    {
        public int Codigo_feedback { get; set; }
        public int Codigo_entrevista { get; set; }

        [Display(Name ="FeedBack")]
        public string Feedback1 { get; set; }
    
        public virtual Interview Interview { get; set; }
    }
}
