//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faps.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Interview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Interview()
        {
            this.Feedback = new HashSet<Feedback>();
        }
    
        public int Codigo_entrevista { get; set; }
        public int Codigo_user { get; set; }
        public string Entrevistador { get; set; }


        [Display(Name = "Data da entrevista:")]
        public System.DateTime Data_Entrevista { get; set; }

        [Display(Name = "Data Criação:")]
        public System.DateTime Data_criacao { get; set; }
        public string Vaga { get; set; }

        [Display(Name = "Status da entrevista")]
        public string Status_interview { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedback { get; set; }
    }
}
