//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Faps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Codigo_log { get; set; }
        public int Codigo_user { get; set; }
        public string Log1 { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
